name: Build and Test

on:
  push:
    branches: [ main ]
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Build with Vite
      run: npm run build
    - name: Build .exe with Rust
      uses: actions-rs/toolchain@v1.2.0
      with:
        toolchain: stable
        override: true
      run: cargo build --release
    - name: Test
      run: npm test
